### ISSUE TITLE
How do I use the program, running it does nothing.

### ISSUE THREAD

**Issue by TheJoetube** [icrayix/lessanvil#2]
I've downloaded the precompiled program and ran it but nothing happened. Is there some other stuff I need to do?
I am on windows 10.

**Comment by icrayix** [comment]
Hi @TheJoetube,

it's CLI program. This means you need a terminal to use it but don't be afraid. It's still quite easy.

1. Download it for your platform (I guess you already followed that step)
2. Open the world folder in the the Windows Explorer
3. Put the previously downloaded program there
4. Do right-click anywhere and press "Open in terminal"
5. Write `lessanvil -w .` in the terminal and press Enter
6. From there on it should guide you through :)

PS: Please do a backup of the world before using the tool

**Comment by TheJoetube** [comment]
> Hi @TheJoetube,
> 
> it's CLI program. This means you need a terminal to use it but don't be afraid. It's still quite easy.
> 
> 1. Download it for your platform (I guess you already followed that step)
> 2. Open the world folder in the the Windows Explorer
> 3. Put the previously downloaded program there
> 4. Do right-click anywhere and press "Open in terminal"
> 5. Write `lessanvil -w .` in the terminal and press Enter
> 6. From there on it should guide you through :)
> 
> PS: Please do a backup of the world before using the tool

Thanks, that worked!
